// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | MapSliceSlice
  | ContactSliceSlice
  | ProjectGridSliceSlice
  | TeamSliceSlice
  | AboutCompanySliceSlice
  | MissionSliceSlice
  | SmallHeroSliceSlice
  | TestimonialsSliceSlice
  | ServicesSliceSlice
  | AboutUsSliceSlice
  | HeroSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Quote field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  quote: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Company name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Place field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.place
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place: prismic.KeyTextField;

  /**
   * Google Map Embed field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.google_map_embed
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_map_embed: prismic.KeyTextField;

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Footer CTA field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_cta: prismic.KeyTextField;

  /**
   * Footer CTA link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *AboutCompanySlice → Default → Primary*
 */
export interface AboutCompanySliceSliceDefaultPrimary {
  /**
   * Overtitle field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About Our Company
   * - **API ID Path**: about_company_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Heading field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Trusted Partner in Construction and Design
   * - **API ID Path**: about_company_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our journey began with a commitment to excellence...
   * - **API ID Path**: about_company_slice.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Feature Text field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Building Trust<br/>Since 1989
   * - **API ID Path**: about_company_slice.default.primary.feature_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature_text: prismic.KeyTextField;

  /**
   * CTA Link field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_company_slice.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image Left field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_company_slice.default.primary.image_left
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_left: prismic.ImageField<never>;

  /**
   * Image Right (Background) field in *AboutCompanySlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_company_slice.default.primary.image_right
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_right: prismic.ImageField<never>;
}

/**
 * Default variation for AboutCompanySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutCompanySliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutCompanySliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutCompanySlice*
 */
type AboutCompanySliceSliceVariation = AboutCompanySliceSliceDefault;

/**
 * AboutCompanySlice Shared Slice
 *
 * - **API ID**: `about_company_slice`
 * - **Description**: AboutCompanySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutCompanySliceSlice = prismic.SharedSlice<
  "about_company_slice",
  AboutCompanySliceSliceVariation
>;

/**
 * Primary content in *AboutUsSlice → Default → Primary*
 */
export interface AboutUsSliceSliceDefaultPrimary {
  /**
   * Heading field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Subheading One field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.subheadingOne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadingOne: prismic.KeyTextField;

  /**
   * Content One field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.contentOne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contentOne: prismic.KeyTextField;

  /**
   * Subheading Two field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.subheadingTwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadingTwo: prismic.KeyTextField;

  /**
   * Content Two field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.contentTwo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contentTwo: prismic.KeyTextField;

  /**
   * Button field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image Left field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.imageLeft
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageLeft: prismic.ImageField<never>;

  /**
   * Image Right field in *AboutUsSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_slice.default.primary.imageRight
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageRight: prismic.ImageField<never>;
}

/**
 * Default variation for AboutUsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsSlice*
 */
type AboutUsSliceSliceVariation = AboutUsSliceSliceDefault;

/**
 * AboutUsSlice Shared Slice
 *
 * - **API ID**: `about_us_slice`
 * - **Description**: AboutUsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceSlice = prismic.SharedSlice<
  "about_us_slice",
  AboutUsSliceSliceVariation
>;

/**
 * Primary content in *ContactSlice → Default → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
  /**
   * Overtitle field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Us
   * - **API ID Path**: contact_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Heading field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Get In Touch
   * - **API ID Path**: contact_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We're here to assist you! Please reach out with any questions, feedback, or project inquiries.
   * - **API ID Path**: contact_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Phone Label field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Phone:
   * - **API ID Path**: contact_slice.default.primary.phone_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_label: prismic.KeyTextField;

  /**
   * Email Label field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email Address:
   * - **API ID Path**: contact_slice.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField;

  /**
   * Location Label field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Location:
   * - **API ID Path**: contact_slice.default.primary.location_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_label: prismic.KeyTextField;

  /**
   * Form Title field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Send Message
   * - **API ID Path**: contact_slice.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_title: prismic.KeyTextField;

  /**
   * Name Placeholder field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Full Name
   * - **API ID Path**: contact_slice.default.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_placeholder: prismic.KeyTextField;

  /**
   * Email Placeholder field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email Address
   * - **API ID Path**: contact_slice.default.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Subject Placeholder field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subject
   * - **API ID Path**: contact_slice.default.primary.subject_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subject_placeholder: prismic.KeyTextField;

  /**
   * Message Placeholder field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Message
   * - **API ID Path**: contact_slice.default.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_placeholder: prismic.KeyTextField;

  /**
   * Submit Button Text field in *ContactSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Submit Message
   * - **API ID Path**: contact_slice.default.primary.submit_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault;

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSlice = prismic.SharedSlice<
  "contact_slice",
  ContactSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Image field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *MapSlice → Default → Primary*
 */
export interface MapSliceSliceDefaultPrimary {
  /**
   * Google Maps Embed URL field in *MapSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.2412648750455!2d-73.98656968459371!3d40.74844097932847!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259a9b3117469%3A0xd134e199a405a163!2sEmpire%20State%20Building!5e0!3m2!1sen!2sus!4v1234567890123!5m2!1sen!2sus
   * - **API ID Path**: map_slice.default.primary.gmaps_embed
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gmaps_embed: prismic.KeyTextField;
}

/**
 * Default variation for MapSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MapSlice*
 */
type MapSliceSliceVariation = MapSliceSliceDefault;

/**
 * MapSlice Shared Slice
 *
 * - **API ID**: `map_slice`
 * - **Description**: MapSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceSlice = prismic.SharedSlice<
  "map_slice",
  MapSliceSliceVariation
>;

/**
 * Primary content in *MissionSlice → Default → Primary*
 */
export interface MissionSliceSliceDefaultPrimary {
  /**
   * Heading field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Subheading One field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.subheading_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading_one: prismic.KeyTextField;

  /**
   * Content One field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.content_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_one: prismic.KeyTextField;

  /**
   * Subheading Two field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.subheading_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading_two: prismic.KeyTextField;

  /**
   * Content Two field in *MissionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_slice.default.primary.content_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_two: prismic.KeyTextField;
}

/**
 * Default variation for MissionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MissionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MissionSlice*
 */
type MissionSliceSliceVariation = MissionSliceSliceDefault;

/**
 * MissionSlice Shared Slice
 *
 * - **API ID**: `mission_slice`
 * - **Description**: MissionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionSliceSlice = prismic.SharedSlice<
  "mission_slice",
  MissionSliceSliceVariation
>;

/**
 * Primary content in *ProjectGridSlice → Default → Primary*
 */
export interface ProjectGridSliceSliceDefaultPrimary {
  /**
   * Overtitle field in *ProjectGridSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Portfolio
   * - **API ID Path**: project_grid_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Heading field in *ProjectGridSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Recent Projects
   * - **API ID Path**: project_grid_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectGridSlice → Items*
 */
export interface ProjectGridSliceSliceDefaultItem {
  /**
   * Project Title field in *ProjectGridSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Name
   * - **API ID Path**: project_grid_slice.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Short Description field in *ProjectGridSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description shown on hover
   * - **API ID Path**: project_grid_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Project Image field in *ProjectGridSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_grid_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectGridSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGridSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGridSliceSliceDefaultPrimary>,
  Simplify<ProjectGridSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectGridSlice*
 */
type ProjectGridSliceSliceVariation = ProjectGridSliceSliceDefault;

/**
 * ProjectGridSlice Shared Slice
 *
 * - **API ID**: `project_grid_slice`
 * - **Description**: ProjectGridSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectGridSliceSlice = prismic.SharedSlice<
  "project_grid_slice",
  ProjectGridSliceSliceVariation
>;

/**
 * Item in *ServicesSlice → Default → Primary → Service*
 */
export interface ServicesSliceSliceDefaultPrimaryServiceItem {
  /**
   * Heading field in *ServicesSlice → Default → Primary → Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.service[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *ServicesSlice → Default → Primary → Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.service[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Button field in *ServicesSlice → Default → Primary → Service*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.service[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ServicesSlice → Default → Primary*
 */
export interface ServicesSliceSliceDefaultPrimary {
  /**
   * Heading field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Content field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Service field in *ServicesSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slice.default.primary.service[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service: prismic.GroupField<
    Simplify<ServicesSliceSliceDefaultPrimaryServiceItem>
  >;
}

/**
 * Default variation for ServicesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSlice*
 */
type ServicesSliceSliceVariation = ServicesSliceSliceDefault;

/**
 * ServicesSlice Shared Slice
 *
 * - **API ID**: `services_slice`
 * - **Description**: ServicesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceSlice = prismic.SharedSlice<
  "services_slice",
  ServicesSliceSliceVariation
>;

/**
 * Primary content in *SmallHeroSlice → Default → Primary*
 */
export interface SmallHeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *SmallHeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *SmallHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_hero_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SmallHeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallHeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallHeroSlice*
 */
type SmallHeroSliceSliceVariation = SmallHeroSliceSliceDefault;

/**
 * SmallHeroSlice Shared Slice
 *
 * - **API ID**: `small_hero_slice`
 * - **Description**: SmallHeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallHeroSliceSlice = prismic.SharedSlice<
  "small_hero_slice",
  SmallHeroSliceSliceVariation
>;

/**
 * Primary content in *TeamSlice → Default → Primary*
 */
export interface TeamSliceSliceDefaultPrimary {
  /**
   * Overtitle field in *TeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meet Our Experts
   * - **API ID Path**: team_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Heading field in *TeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dedicated Professionals
   * - **API ID Path**: team_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *TeamSlice → Items*
 */
export interface TeamSliceSliceDefaultItem {
  /**
   * Name field in *TeamSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team Member Name
   * - **API ID Path**: team_slice.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TeamSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Job Title
   * - **API ID Path**: team_slice.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Description field in *TeamSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: One sentence about this team member
   * - **API ID Path**: team_slice.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *TeamSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TeamSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceSliceDefaultPrimary>,
  Simplify<TeamSliceSliceDefaultItem>
>;

/**
 * Slice variation for *TeamSlice*
 */
type TeamSliceSliceVariation = TeamSliceSliceDefault;

/**
 * TeamSlice Shared Slice
 *
 * - **API ID**: `team_slice`
 * - **Description**: TeamSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceSlice = prismic.SharedSlice<
  "team_slice",
  TeamSliceSliceVariation
>;

/**
 * Item in *TestimonialsSlice → Default → Primary → Testimonial*
 */
export interface TestimonialsSliceSliceDefaultPrimaryTestimonialItem {
  /**
   * Name field in *TestimonialsSlice → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.testimonial[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *TestimonialsSlice → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.testimonial[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Content field in *TestimonialsSlice → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.testimonial[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *TestimonialsSlice → Default → Primary*
 */
export interface TestimonialsSliceSliceDefaultPrimary {
  /**
   * Heading field in *TestimonialsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Overtitle field in *TestimonialsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.overtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtitle: prismic.KeyTextField;

  /**
   * Testimonial field in *TestimonialsSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for TestimonialsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialsSlice*
 */
type TestimonialsSliceSliceVariation = TestimonialsSliceSliceDefault;

/**
 * TestimonialsSlice Shared Slice
 *
 * - **API ID**: `testimonials_slice`
 * - **Description**: TestimonialsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSlice = prismic.SharedSlice<
  "testimonials_slice",
  TestimonialsSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AboutCompanySliceSlice,
      AboutCompanySliceSliceDefaultPrimary,
      AboutCompanySliceSliceVariation,
      AboutCompanySliceSliceDefault,
      AboutUsSliceSlice,
      AboutUsSliceSliceDefaultPrimary,
      AboutUsSliceSliceVariation,
      AboutUsSliceSliceDefault,
      ContactSliceSlice,
      ContactSliceSliceDefaultPrimary,
      ContactSliceSliceVariation,
      ContactSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      MapSliceSlice,
      MapSliceSliceDefaultPrimary,
      MapSliceSliceVariation,
      MapSliceSliceDefault,
      MissionSliceSlice,
      MissionSliceSliceDefaultPrimary,
      MissionSliceSliceVariation,
      MissionSliceSliceDefault,
      ProjectGridSliceSlice,
      ProjectGridSliceSliceDefaultPrimary,
      ProjectGridSliceSliceDefaultItem,
      ProjectGridSliceSliceVariation,
      ProjectGridSliceSliceDefault,
      ServicesSliceSlice,
      ServicesSliceSliceDefaultPrimaryServiceItem,
      ServicesSliceSliceDefaultPrimary,
      ServicesSliceSliceVariation,
      ServicesSliceSliceDefault,
      SmallHeroSliceSlice,
      SmallHeroSliceSliceDefaultPrimary,
      SmallHeroSliceSliceVariation,
      SmallHeroSliceSliceDefault,
      TeamSliceSlice,
      TeamSliceSliceDefaultPrimary,
      TeamSliceSliceDefaultItem,
      TeamSliceSliceVariation,
      TeamSliceSliceDefault,
      TestimonialsSliceSlice,
      TestimonialsSliceSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceSliceDefaultPrimary,
      TestimonialsSliceSliceVariation,
      TestimonialsSliceSliceDefault,
    };
  }
}
