// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_company_slice: dynamic(() => import("./AboutCompanySlice")),
  about_us_slice: dynamic(() => import("./AboutUsSlice")),
  contact_slice: dynamic(() => import("./ContactSlice")),
  cta_slice: dynamic(() => import("./CtaSlice")),
  gallery_slice: dynamic(() => import("./GallerySlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  map_slice: dynamic(() => import("./MapSlice")),
  mission_slice: dynamic(() => import("./MissionSlice")),
  project_grid_slice: dynamic(() => import("./ProjectGridSlice")),
  rich_text_slice: dynamic(() => import("./RichTextSlice")),
  service_detail_slice: dynamic(() => import("./ServiceDetailSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
  small_hero_slice: dynamic(() => import("./SmallHeroSlice")),
  team_slice: dynamic(() => import("./TeamSlice")),
  testimonials_slice: dynamic(() => import("./TestimonialsSlice")),
};
